### ISSUE TITLE
Building Hiding not updating.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#198] opened 2021-06-15 21:40 UTC
Alpha 4 - Build 57

When the game is paused and you rotate the camera over a building to hide it, it hides, however when you move the camera away it doesn't show again, until you unpause the game again. 

(Needs video please @Gerwanese :) )

**Comment by Gerwanese** [comment] 2021-06-15 22:45
Duplicate of #167 :)

**Closed by Gerwanese** 2021-06-15 22:45 UTC
Labels: duplicate
