### ISSUE TITLE
Filling up shops: First box has double the content of further boxes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#182] opened 2021-06-13 22:40 UTC
Build 55

When placing several boxes of clothes onto a rack, the first box will stock up 100 items and every further box only 50 items.
The same happens for paper bags at cash registers, fresh food at industrial fridge etc, probably everywhere the same.

https://user-images.githubusercontent.com/17579552/121823985-1fcd0000-cca9-11eb-894e-87ca87596530.mp4

**Comment by jhovgaard** [comment] 2021-07-06 15:34
Couldn't reproduce, but this has been completed rewritten. Expected it was fixed in build 74.

**Closed by jhovgaard** 2021-07-06 15:34 UTC
Labels: confirmed
