### ISSUE TITLE
game save

### ISSUE THREAD

**Issue by Shachare** [hovgaardgames/bigambitions-public#397] opened 2021-08-01 14:04 UTC
saving the game while playing,
after closing the game the game disappeared from the saved games in the main menu.

**Comment by Gerwanese** [comment] 2021-08-01 15:55
@Shachare Can you check what files are in your savegame folder?
The folder is located at `C:\Users\<USERNAME>\AppData\LocalLow\Hovgaard Games\Big Ambitions`
<USERNAME> has to be replaced with your Windows username.
The `AppData` folder is hidden, so if it's not shown in your explorer, you might have to add it manually to the path:
![grafik](https://user-images.githubusercontent.com/17579552/127777372-70ac2019-9640-4bf2-83c6-64ba2a511690.png)

**Comment by jhovgaard** [comment] 2021-09-09 13:40
I couldn't reproduce this. Closing for now :-)

**Closed by jhovgaard** 2021-09-09 13:40 UTC
