### ISSUE TITLE
Pedestrians spawning in visible area

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#310] opened 2021-07-13 21:28 UTC
Build 78

Pedestrians are spawning in the visible area.

See in the video at the top left corner of the street crossing (where the two stuck people are standing). First person spawning at 18 seconds into the video, more people later on.

[Build78-SpawningIssue.txt](https://github.com/hovgaardgames/bigambitions-public/files/6812150/Build78-SpawningIssue.txt)

https://user-images.githubusercontent.com/17579552/125527600-b69072bd-8338-4d76-bde0-6191af6fe493.mp4

**Comment by jhovgaard** [comment] 2021-07-14 13:46
Couldn't reproduce, but indirectly (hopefully) fixed by another spawning issue.  Build 79

**Closed by jhovgaard** 2021-07-14 13:46 UTC
Labels: confirmed
