### ISSUE TITLE
Player keeps running on the spot although there's free space in front after car contact

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#57] opened 2021-04-28 23:27 UTC
Alpha 3 - Build 12

https://i.adameg.net/EtBZAi.mp4   (Same video as previous issue report, but different issue)

Towards the end of the video the player running animation keeps playing even though it doesn't run anywhere

**Comment by Gerwanese** [comment] 2021-04-28 23:56
I think the player animation is correct because the player still tries to reach the position where you first click (he will keep running until reaching the position).
The bug here rather seems to be that there's suddenly a distance between you and the car which wasn't there before.
I know that sometimes there's a problem with sudden position changes (the car sometimes moves a bit when leaving it too) however I was never able to reproduce any of these. Have to keep it on "cannot reproduce" for now.

**Comment by adameg2305** [comment] 2021-04-29 00:08
It is hard to reproduce, however, the easiest way I've found to reproduce is related to issue #56 it is when the player runs towards a moving vehicle and then the car stops so it doesn't hit the player. for some reason, the player still tries to run towards the car (Or where the player clicked) but it blocked by an invisible barrier

**Comment by Gerwanese** [comment] 2021-04-29 00:30
I couldn't reproduce it your way, but in a different way I could do it as often as I wanted.
1. Stand in front of a car so it stops for you
2. Click somewhere behind the car to start running against it
3. Wait for the car to get a little speed (otherwise it didn't work)
4. Click somewhere in front of the car with a bit of a distance
The player will then start running towards that last clicked spot, but after about half way he will suddenly stop, turn around and have the running animation towards the car for a short moment. The duration seems to depend a bit on the previous speed, not 100% sure about this.

https://user-images.githubusercontent.com/17579552/116488325-6c43b400-a892-11eb-862b-b76b72115866.mp4

**Comment by jhovgaard** [comment] 2021-05-31 11:51
Fixed in build 49

**Closed by jhovgaard** 2021-05-31 11:51 UTC
Labels: confirmed, low-priority
