### ISSUE TITLE
Furniture store - Walking through walls possible

### ISSUE THREAD

**Issue by Zatoici** [hovgaardgames/bigambitions-public#536] opened 2021-09-04 15:46 UTC
Build 184

https://user-images.githubusercontent.com/90038819/132100318-bc88461c-f0de-474d-aad7-4102789109a7.mp4

**Comment by jokoho48** [comment] 2021-09-04 15:47
duplicate of https://github.com/hovgaardgames/bigambitions-public/issues/490

**Closed by jokoho48** 2021-09-04 15:47 UTC
Labels: duplicate
