### ISSUE TITLE
Traffic pileups

### ISSUE THREAD

**Issue by ChrisB-M** [hovgaardgames/bigambitions-public#34] opened 2021-04-26 13:58 UTC
Going about my normal day to day business as a business owner and the traffic sure does get worse in Hells Kitchen over time

![traffic pileups](https://user-images.githubusercontent.com/6843892/116094349-5f12a380-a69f-11eb-8706-873c06a31f18.PNG)

![traffic 2](https://user-images.githubusercontent.com/6843892/116094791-bd3f8680-a69f-11eb-8cdf-dcdbd3832732.PNG)

**Comment by ChrisB-M** [comment] 2021-04-26 14:06
![traffic 3](https://user-images.githubusercontent.com/6843892/116096205-ffb59300-a6a0-11eb-9371-6474f9c73964.PNG)

**Comment by Gerwanese** [comment] 2021-04-26 15:16
Duplicate of #3 
Fix already in progress as far as I know.

**Closed** 2021-04-26 21:03 UTC
Labels: duplicate
