### ISSUE TITLE
Cant Purchase Mop

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#140] opened 2021-06-04 17:15 UTC
Alpha 4 - Build 

In the appliance store, you cant reach the mop as the gap between the cash register and freezer is too small.

**Comment by Gerwanese** [comment] 2021-06-04 20:44
Confirmed. It is probably caused by the recent moving of "Industrial Fridge" down a bit to make the hand truck more accessible.

**Comment by jhovgaard** [comment] 2021-06-05 08:06
Fixed in build 52

**Closed by jhovgaard** 2021-06-05 08:06 UTC
Labels: confirmed
