### ISSUE TITLE
Juddery Shaddows

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#128] opened 2021-06-01 19:21 UTC
Alpha 4 - Build 49

Shadows appear to judder across the screen when looking at an object closely,
https://i.adameg.net/4b5kEZ.jpg Also when they are moving gives a sort of jumping clockwise (For lack of better explanation) efffect. 
Not sure how much can be done, but thought best mention.

**Comment by Gerwanese** [comment] 2021-06-01 19:31
Might be duplicate of #40 but I'll leave the decision to @jhovgaard

**Comment by jhovgaard** [comment] 2021-06-10 14:26
They are the same yes :) Closing

**Closed by jhovgaard** 2021-06-10 14:26 UTC
Labels: confirmed
