### ISSUE TITLE
Job Timings Wrong

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#129] opened 2021-06-01 19:24 UTC
Alpha 4 - Build 49

When applying for a job, you get the stores opening hours instead of the actual hours the player will work. Would most likely lead to confusion.
https://i.adameg.net/50Et1B.png

**Comment by Gerwanese** [comment] 2021-06-01 19:29
Duplicate of #9.

**Closed by Gerwanese** 2021-06-01 19:29 UTC
Labels: duplicate
