### ISSUE TITLE
When I got out of my car while driving to the exit off the wholesale store I exited while my van is still inside 

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#295] opened 2021-07-07 14:47 UTC
When I got out of my car while driving to the exit off the wholesale store I exited while my van is still inside. And now i cant re-enter the store.
Build 75.
[Build 75  Wholesale store BUG.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778106/Build.75.Wholesale.store.BUG.txt)

**Comment by Gerwanese** [comment] 2021-07-07 15:10
I can verify that you are outside, the car inside if you jump out of the car just before the exit (while rolling towards it).
In my savegame I was able to get in again.

[Build75-DriveInKickedOut.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778286/Build75-DriveInKickedOut.txt)


https://user-images.githubusercontent.com/17579552/124784418-34b64f80-df46-11eb-91b0-aca5596ae471.mp4

**Comment by jhovgaard** [comment] 2021-07-15 16:44
I couldn't reproduce either :/ @tomvbj are you able to re-produce it again? Maybe you can provide a video?

**Comment by Gerwanese** [comment] 2021-07-15 18:14
Build 78

I just reproduced the whole thing with the Merc.
Now I'm stuck outside of the drive-in store (probably because the area in front is now "building" area and you can't walk on it anymore).

Important for reproduction: Drive onto the door with some speed and make sure you hit the "park vehicle" button just a very short time before the car hits the door. If the car already hit the door, you're immediately stopped so it won't happen. If you hit the button too early, you don't get pushed far enough to be outdoors.

[Build78-BeamMeUpMercy!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6825372/Build78-BeamMeUpMercy.txt)


https://user-images.githubusercontent.com/17579552/125837144-9f1bd183-3d01-4065-891b-3bcb638d6fab.mp4

**Comment by jhovgaard** [comment] 2021-07-19 10:48
Fixed in build 79

**Closed by jhovgaard** 2021-07-19 10:48 UTC
Labels: confirmed
