### ISSUE TITLE
Business's EconoView not showing Salaries on statement

### ISSUE THREAD

**Issue by ChrisMayhew** [hovgaardgames/bigambitions-public#394] opened 2021-07-31 22:51 UTC
![Untitled](https://user-images.githubusercontent.com/9767399/127754139-7abb2e0f-3857-4eff-b004-4e25df49696f.png)

As shown above, the Ongoing Expenses of a business doesn't show any value for Salaries even though I have an employee at this business so it's hard to see if I'm actually making any real profit or not.

Game Build 130 (Alpha 5)

**Comment by ChrisMayhew** [comment] 2021-07-31 22:56
Seems this may have been fixed in the last update because after running a game day more it's showing a salary now.

**Comment by Gerwanese** [comment] 2021-07-31 22:59
This is a duplicate of bug #315 
The salary is paid at 00:00, so it is calculated for the next day (although it is paid for the previous day). Definitely a bug that should be fixed, but as we already have it reported I will close this one.

**Closed by Gerwanese** 2021-07-31 22:59 UTC
Labels: duplicate
