### ISSUE TITLE
Seizure while sleeping

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#133] opened 2021-06-04 16:29 UTC
Alpha 4 - Build 51

While sleeping your feet are shaking/ vibrating. 

Cant get a good video.

**Comment by Gerwanese** [comment] 2021-06-04 20:23
Could not reproduce this, my legs were absolutely dead and sleeping. Will have to put cannot-reproduce for now.

**Comment by jhovgaard** [comment] 2021-06-05 08:02
It might only be visible on higher resolutions, but I can see it.

It's the sleeping animation running at a higher speed to simulate fast-forward sleeping. I'll look into slowing it down a bit.

**Comment by jokoho48** [comment] 2021-09-14 20:41
Fixed with new Timemachine Implementation.

**Closed by jokoho48** 2021-09-14 20:41 UTC
Labels: confirmed, low-priority
