### ISSUE TITLE
Player phases through buildings when autopathing

### ISSUE THREAD

**Issue by JacYosAkiCra** [hovgaardgames/bigambitions-public#395] opened 2021-08-01 03:50 UTC
Build: BA Alpha 5 (Build 130)
Problem: Went from wholesale store back to my store near my home. Set store as destination, character started moving, then decided to run through a building (phased) into the woods. Was able to get back on street by phasing through building. Also couldn't highlight the building I phased through on voogle maps.

![Screenshot (16)_LI](https://user-images.githubusercontent.com/43555292/127758549-f5f94e7d-a844-453f-9f04-1c4166627672.jpg)

**Comment by Gerwanese** [comment] 2021-08-01 09:56
Duplicate of #97

**Closed by Gerwanese** 2021-08-01 09:56 UTC
Labels: duplicate
