### ISSUE TITLE
Sign Editor Selction displays all previously selected not current selected

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#601] opened 2021-10-12 16:41 UTC
### Build number

223

### Bug description

When selecting anything in the sign editor it won't remove the previously selected icon so you will end up with all of them selected on the display but not on the actual sign.

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/136996253-8e92bd94-7f2f-4a2b-b8b2-fa21b370b9be.mp4

**Comment by jhovgaard** [comment] 2021-10-13 08:34
I couldn't reproduce either. It's caused by some other error that happened before this.

I noticed the sign says "Available for rent". @adameg2305 did you rent the building before, or could you access the sign appearance without?

Closing for now until we figure out how to reproduce.

**Closed by jhovgaard** 2021-10-13 08:34 UTC
Labels: cannot-reproduce
