### ISSUE TITLE
26 Third Street building outline just covering half of it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#97] opened 2021-05-31 22:45 UTC
Build 49

The outline of the building 26 Third Street is just covering half of it. The other half doesn't have any overlay.
It may be due to two doors, however other buildings with two doors have one layover covering all of it.

![grafik](https://user-images.githubusercontent.com/17579552/120247032-6d417a00-c272-11eb-9f52-a8057b8cc547.png)

**Comment by jhovgaard** [comment] 2021-06-11 07:18
It is actually two different buildings, just randomly having the same color :D

The second one should show as number 24 now.

**Comment by Gerwanese** [comment] 2021-06-13 19:18
Unfortunately have to reopen this. It's now shown as two buildings, but the shop in number 24 also shows up in 26.

https://user-images.githubusercontent.com/17579552/121819346-d373c700-cc8c-11eb-92e6-d3ee63c1c51e.mp4

**Comment by Gerwanese** [comment] 2021-07-06 23:20
Can still confirm in build 75. The building no. 24 also is not selectable on Voogle Maps. Even if there's a generated business inside it's inaccessible.

**Comment by Gerwanese** [comment] 2021-07-28 21:44
Issue got worse in build 106, see #350 

[106save.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896569/106save.txt)

https://user-images.githubusercontent.com/44293115/127399166-fac72fd8-4156-4500-894e-16accc07d2b1.mp4

**Comment by Gerwanese** [comment] 2021-08-01 09:55
Additionally to the building above (24 Third Street), the following buildings - all on Third Street - are affected as well:

![grafik](https://user-images.githubusercontent.com/17579552/127766716-233929e0-0069-4ed4-8d0b-0e70cbbd2a8a.png)

Moving this to alpha 5 as it gets reported quite frequently.

**Comment by jhovgaard** [comment] 2021-08-02 17:19
I wasn't able to reproduce any of these. Might have been fixed in between, or caused by old savegames.

Please confirm and close if I'm right.

**Comment by Gerwanese** [comment] 2021-08-02 20:13
I guess the video tells the story... Not fixed at all. :)

https://user-images.githubusercontent.com/17579552/127918086-3b7feb54-3ed2-4f06-ab2c-b22b67980056.mp4

**Comment by jhovgaard** [comment] 2021-08-04 08:49
Fixed in build 135.

It caused quite a big rewrite and multiple buildings had to be remodeled. I expect lots of issues with other buildings.

Please reopen and include addresses. Savegame not required :)

**Closed by jhovgaard** 2021-08-04 08:49 UTC
Labels: confirmed
