### ISSUE TITLE
Cant click on building when partially hidden

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#75] opened 2021-05-30 18:15 UTC
Alpha 4 - Build 47

https://i.adameg.net/7XEhDX.jpg - When hidden cant hover over the building to enter

https://i.adameg.net/Eo1CBc.jpg - When not hidden can click and hover over it.

(Sorry cant record video for it)

**Comment by jhovgaard** [comment] 2021-05-31 10:12
Hmm I see the issue. It's complicated to "fix" as it is by design to ensure you can click the ground behind buildings if they are hidden. 

Let's keep this open and see if it's still an issue once the new camera controls are in place.

**Comment by Gerwanese** [comment] 2021-05-31 21:33
Closed #88 and instead moved the content here:

When the upper floors are hidden it's not possible to enter the building.
See the two cases in video.
In the second case it's additionally also difficult to "catch" the building next door although all floors are shown. You have to find a small area where the interaction overlay shows up.

https://user-images.githubusercontent.com/17579552/120243631-69a8f580-c268-11eb-8e4d-41f25c5caafc.mp4


https://user-images.githubusercontent.com/17579552/120243652-7b8a9880-c268-11eb-88af-8f2ecbb59f0e.mp4

**Comment by Gerwanese** [comment] 2021-07-01 20:47
Issue has changed a bit with the new system where buildings are completely hidden.
In build 70 you could still enter buildings from any side even when hidden. In build 71 it's not possible anymore and the building overlay doesn't show up when the building is hidden.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750693/Build71.txt)

**Comment by jhovgaard** [comment] 2021-07-06 12:36
Fixed in build 75

**Closed by jhovgaard** 2021-07-06 12:36 UTC
Labels: confirmed, low-priority
