### ISSUE TITLE
Blurry View After Opening Bizview

### ISSUE THREAD

**Issue by amassivecont** [hovgaardgames/bigambitions-public#373] opened 2021-07-30 19:05 UTC
After opening bizview and trying to enter the building at the same time the bizview menu opned and to close it i had to click close several times each time the menu became more opaque until i was left with a blurry view of the world 
![image](https://user-images.githubusercontent.com/88209621/127700341-b7191526-cb45-4fb8-b158-f374fdbecc52.png)

**Comment by adameg2305** [comment] 2021-07-30 19:06
#356 @Gerwanese

**Comment by Gerwanese** [comment] 2021-07-30 19:25
Duplicate of #356

**Closed by Gerwanese** 2021-07-30 19:25 UTC
Labels: duplicate
