### ISSUE TITLE
Building Tags not updating if already hovering over it.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#260] opened 2021-07-03 16:09 UTC
Alpha 4 - Build 73 

When hovering over a building's info tab before it opens it displays the "Closed" message and then the building opens for business the tab doesnt update, so still shows the "Closed" Version.

**Comment by Gerwanese** [comment] 2021-07-03 17:08
Could verify this for closing shop but not opening. It seems it doesn't occur all the time but there's definitely an issue.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758750/Build71.txt)


https://user-images.githubusercontent.com/17579552/124361754-fdd3f700-dc30-11eb-9edb-f73d167988ee.mp4

**Comment by Gerwanese** [comment] 2021-07-03 18:33
Could now confirm the same issue for opening time as well. The mouse had to be below the "Open in BizMan" button, where the "Click to enter" text would appear.

**Comment by jokoho48** [comment] 2021-09-14 00:12
I can't reproduce in the latest build. please reopen if it still happens and because the whole system of hovering and selection items and Buildings was rewritten a few builds back I would say, Fixed in the meanwhile.

**Closed by jokoho48** 2021-09-14 00:12 UTC
Labels: confirmed
