### ISSUE TITLE
Shortcuts: "Space" doesn't pause game after opening and closing building details

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#12] opened 2021-04-25 14:48 UTC
After opening and closing the details of a building, pressing "Space" will not pause/unpause the game but instead open the details again. Only after clicking somewhere else, the shortcut will work as intended again.
If clicking "Space" with already open details, there will be a short flickering (probably the detail screen reopening again).

**Comment by jhovgaard** [comment] 2021-06-11 07:48
I couldn't reproduce. @Gerwanese will you check and close if it has been fixed?

**Comment by Gerwanese** [comment] 2021-06-13 19:33
I had the feeling that it once happened again to me with two people at the same time, but can't really reproduce. Will close it for now.

**Comment by Gerwanese** [comment] 2021-06-13 19:34
Seems to be fixed.

**Comment by Gerwanese** [comment] 2021-06-13 21:12
Reopening, found the issue.
If you open any phone app (and the building details are opened in BizMan) and closing through pressing ESC, then pressing Space will reopen the app again.
If you close the details through clicking "Close" than this doesn't happen.

**Comment by Gerwanese** [comment] 2021-06-15 23:31
Additional information:
This is related to the phone app icon keeping the focus.
If you open a phone app the focus will still stay on the clicked icon. That's why when the app is open and you press Space, the screen will be flickering - because it triggers another click on the app icon.
If you close with ESC instead of clicking, the focus is still on the icon. It thus still triggers the dialog unless you click anywhere else.
In Voogle Maps the effect is even stronger because if you open it through clicking the icon and then press Space while Voogle Maps is open, the app will close (obviously here the "click" on the icon doesn't always trigger the "open" action but instead the "switch open/close" action).

**Comment by jokoho48** [comment] 2021-09-14 13:55
Fixed in Build 192

**Closed by jokoho48** 2021-09-14 13:55 UTC
Labels: confirmed
