### ISSUE TITLE
Hired 2 employees - cannot assign them different shifts...

### ISSUE THREAD

**Issue by ChrisB-M** [hovgaardgames/bigambitions-public#31] opened 2021-04-26 13:14 UTC
I hired 2 employees and for the auto-generated shifts, it will allow me to assign 1 employee to both shifts but will never let you have different employees in shifts. It seems to auto-fill employees to all shifts - even those taken by other employees.

Unassigned works as intended and doesn't autofill.

![shift bug 1](https://user-images.githubusercontent.com/6843892/116088224-95e5bb00-a699-11eb-9a28-50253d470ad5.PNG)
![shift bug 2](https://user-images.githubusercontent.com/6843892/116088229-967e5180-a699-11eb-9447-e9d7de202e51.PNG)
![shift bug 3](https://user-images.githubusercontent.com/6843892/116088230-9716e800-a699-11eb-930b-3a0750710f6f.PNG)

**Comment by Gerwanese** [comment] 2021-04-26 15:09
Duplicate of #19

**Closed** 2021-04-26 21:03 UTC
Labels: duplicate
