### ISSUE TITLE
NPC's despawning infront of the drive-in wholesale store.

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions-public#195] opened 2021-06-14 19:48 UTC
If you stand nearby the drive-in wholesale store you can see the npc's despawning. 
expected to despawn some where that you can't see. 
isn't related to the drive-in wholesale store but as people will go the store they will see it. 
Not a major issue just a mention for more realistic gameplay.

https://user-images.githubusercontent.com/85610694/121950600-22d3f900-cd5a-11eb-873b-aab3d17c1aaa.mp4

**Comment by Gerwanese** [comment] 2021-06-14 19:53
Duplicate of #115 - not a bug but by design according to the comment there.

**Closed by Gerwanese** 2021-06-14 19:53 UTC
