### ISSUE TITLE
Interviewed person can leave during interview

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#5] opened 2021-04-25 14:15 UTC
When interviewing a person waiting at a red traffic light, the person will walk away on green light.
Another situation is the interviewed person being pushed away by another person running into him/her.

In both cases the protagonist of the game is stuck (without being able to see any interview progress).
The problem can be solved by clicking on another pedestrian. The protagonist will then walk towards that person and do another interview, afterwards moving is possible again.

**Comment by ChrisB-M** [comment] 2021-04-26 14:37
Related to this issue: sometimes if you brush past a person, the interview will trigger and stop your character but nothing will happen and the citizen just continues his walk. You are frozen in place and unable to move (can be broken by restarting or by triggering another interview with a nearby passerby)

**Comment by jhovgaard** [comment] 2021-06-11 07:58
I couldn't reproduce. Might have been indirectly fixed in build 54.

**Comment by Gerwanese** [comment] 2021-06-13 19:01
Unfortunately still valid in Build 55 although the timing got more difficult now.

https://user-images.githubusercontent.com/17579552/121818904-724af400-cc8a-11eb-8fb3-c873bd32729c.mp4

**Comment by jhovgaard** [comment] 2021-06-19 10:12
Fixed in build 66

**Closed by jhovgaard** 2021-06-19 10:12 UTC
Labels: confirmed
