### ISSUE TITLE
Similar to #27. Some items can exist in a state of "placed and not-placed"

### ISSUE THREAD

**Issue by ChrisB-M** [hovgaardgames/bigambitions-public#32] opened 2021-04-26 13:24 UTC
Easiest to explain. Sometimes store items get to a place where if you press place it puts them down without offering you the snap grid but the item still appears to be held and you cannot move it - only option is to discard it.

Items I have encountered this with - 
1. Drinks Fridge
2. (After Drinks Fridge broke it) Cash register couldn't be moved (but could be rotated) 
3. (After Drinks Fridge broke it) Mop exhibited same behaviour

SS after mop

![mop](https://user-images.githubusercontent.com/6843892/116089782-18bb4580-a69b-11eb-8ac6-e31aae3cfff2.PNG)

**Comment by Gerwanese** [comment] 2021-04-26 15:11
Duplicate of #27

**Closed** 2021-04-26 21:03 UTC
Labels: duplicate
