### ISSUE TITLE
Faster than normal camera rotation

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#402] opened 2021-08-01 16:51 UTC
Alpha 5 - Build 130

When holding right click and moving your mouse to rotate your camera, if you are next to the building highlighted in red in the image below, your camera rotation moves a lot faster than normal, also shown in the video.

![image](https://user-images.githubusercontent.com/44293115/127778966-fb14ab80-d6b2-4d68-bb43-62e3d9d35081.png)

https://user-images.githubusercontent.com/44293115/127779030-ead6e8be-984e-45a1-875f-022529c78656.mp4

**Comment by Gerwanese** [comment] 2021-08-01 17:51
Confirmed. Generally rotation speed is faster when the mouse is further away from the player/center of screen, but there's still an additional speed difference for this specific building. Maybe because it's costly to render and removing it will speed up things? Although you can see that the fast rotation massively reduces fps...

[Build130-RotateRotateRotateTheNextRideWillGoBackwards!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6913122/Build130-RotateRotateRotateTheNextRideWillGoBackwards.txt)

**Comment by jokoho48** [comment] 2021-09-11 15:24
Fixed in 187.

**Closed by jokoho48** 2021-09-11 15:24 UTC
Labels: confirmed
