### ISSUE TITLE
I hard crash your game

### ISSUE THREAD

**Issue by MrBor** [hovgaardgames/bigambitions-public#443] opened 2021-08-06 12:08 UTC
Hi there!

Thanks for helping out getting rid of the bugs 🕷

**First thing, make sure your bug is not already reported. I don't want you to waste your time 😇**

Secondly, if possible please include a screenshot or a video, that's always nice.

Lastly, include the build number you found the bug in. You can see it in the top right corner of the game.

Thanks again!

**This message should be deleted before submitting the bug.**

Hi 
I restarted my game play
How would the game hands if someone speed run it I got upto 7 days before the game freezers. These are the steps I took. I got the thing which need to start the game then got my job at the corner store. I got home go to sleep for 13 to 14 hours then go to work if need to eat then buy a food item eat it then discard if not the wait for work to start. Use the time machine. I did this until I got to the bank Second i sat down the game fully frozen. I tried to return to the main menu it pop-up. But it could not do anything. I had use the task manager to close the game down.
Sorry for breaking your game.😅

**Comment by MrBor** [comment] 2021-08-06 17:29
Hi @Gerwanese 
That's fine and don't worry i will be playing it right because i can not enough a new gpu 😅.
I will try and get that for you sadly can't do it right now because I work on weekends nights 8:30pm to 7am. I will try and get it to you soon as possible.

**Comment by MrBor** [comment] 2021-08-11 19:17
[Player.log](https://github.com/hovgaardgames/bigambitions-public/files/6970825/Player.log)
[Player-prev.log](https://github.com/hovgaardgames/bigambitions-public/files/6970826/Player-prev.log)

Hi @Gerwanese 
Sorry it taken this long to get back to you. I did not know which one you needed.
So I put both of them in. If you need anything else. Let me know I will send it right anyway or soon was I can.

**Comment by Gerwanese** [comment] 2021-08-11 19:24
@jhovgaard Can you see anything from the logfiles? I see lots of errors but don't know if any of them is a serious one.

**Comment by MrBor** [comment] 2021-08-11 19:38
I deleted the gameplay would effect the logfile?

**Comment by MrBor** [comment] 2021-08-11 20:54
@Gerwanese Hi I found this new bug only I can fix it by clicking on the bed. It started two game days ago I don't know if the supermarket ran out of paper bag. did not show that I had paperbag but I could not pick up shoppingbasket. I left the store it show that I got the items. I could not put them in fridge. So I had to discards them. I made my character go to bed. Then next day when my character got up the game frozen I press everywhere it would not respond. Until I press on the bed then press cancel. Which look like it fix it. But I gone to the supermarket again to get some more food items did same again could not see any items which I was picking up but still could pay for the items. Got two fresh food and two frozen food items. I left the store but this time it show my items in a shoppingbasket which I could not place in the fridge so I place the basket on the ground. This time I was playing the game the right way.
![20210811_213019 1](https://user-images.githubusercontent.com/88434315/129098915-efa8b384-b7fc-448f-9bea-9087fa6eb095.jpg)

**Comment by MrBor** [comment] 2021-08-11 20:59
I can try making my character get in to bed canceling it again. Saving it and see it that fixed the problem for now?

**Comment by MrBor** [comment] 2021-08-11 22:22
@Gerwanese Hi sorry about this I don't mean to bug you with this. But I tried save the game see if this fixed the bug and the answer is no. Now can not pause my game look I need to restart the game which is fine. Have so picture hopeful this will help.
At four different time stages

![20210811_231408 1](https://user-images.githubusercontent.com/88434315/129110797-0facd371-fc3e-4891-a697-04a0a3fdb98d.jpg)
![20210811_231443 1](https://user-images.githubusercontent.com/88434315/129110839-6df05fe0-ae52-4ce1-8905-4dd53dd8d059.jpg)
![20210811_231443 1](https://user-images.githubusercontent.com/88434315/129110882-47118684-209d-4464-8cf9-747130860ea4.jpg)
![20210811_232017 1](https://user-images.githubusercontent.com/88434315/129111057-73ab15c1-fe36-4836-bc42-c85377e244ba.jpg)

**Comment by MrBor** [comment] 2021-08-11 22:23
sorry put on of them two time
![Uploading 20210811_231452[1].jpg…]()

**Comment by MrBor** [comment] 2021-08-11 22:24
sorry put on of them two time
![20210811_231452 1](https://user-images.githubusercontent.com/88434315/129111554-e007bcfc-6661-4233-be4b-e59a9227b506.jpg)

**Comment by Gerwanese** [comment] 2021-08-12 14:35
Hi @MrBor, we can see from your logfiles that your installation is corrupt. Can you do the file integrity check on Steam and check if the problem is solved with that?
![grafik](https://user-images.githubusercontent.com/17579552/129215572-9e2d6a95-81d9-4530-b91c-29f409b114bf.png)
![grafik](https://user-images.githubusercontent.com/17579552/129215675-94244de5-2685-4bd7-9641-fb1aa2f0e263.png)

**Comment by MrBor** [comment] 2021-08-12 14:37
yeah that fine

**Comment by MrBor** [comment] 2021-08-12 14:41
@Gerwanese I have done it now anything else I can help with just let me know

**Comment by Gerwanese** [comment] 2021-08-12 15:35
@MrBor Is the problem still there or is everything fine now?

**Comment by MrBor** [comment] 2021-08-12 16:26
@Gerwanese yeah that fix the bug

**Comment by MrBor** [comment] 2021-08-12 16:26
Thank you

**Comment by Gerwanese** [comment] 2021-08-12 16:30
Alright, perfect. I'll close this bug.

**Closed by Gerwanese** 2021-08-12 16:30 UTC
