### ISSUE TITLE
Number of boxes on hand truck not updating when using removing one

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#92] opened 2021-05-31 22:05 UTC
Build 49

After removing the food from the hand truck and only having the fridge left, it still shows two boxes.
This only seems to happen with a food paper bag on the truck so it might be fixed together with #83 if paper bags don't become boxes anymore.

![grafik](https://user-images.githubusercontent.com/17579552/120243029-c0adcb00-c266-11eb-89c5-773cd4945ac8.png)

**Comment by jhovgaard** [comment] 2021-06-13 15:00
Unable to reproduce. I'm pretty sure this was indirectly fixed in an earlier build.

**Closed by jhovgaard** 2021-06-13 15:00 UTC
Labels: confirmed
