### ISSUE TITLE
Getting Paid to much.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#235] opened 2021-06-23 13:37 UTC
Alpha 4 - Build 67

Im getting paid $25 an hour for a job which i was told i was getting $12. This is the first job at El Gato foods.
![vgTXjq](https://user-images.githubusercontent.com/44293115/123106487-90ee7f00-d430-11eb-86d2-b646250ee692.png)

**Comment by Gerwanese** [comment] 2021-06-23 22:20
Possible duplicate of #9 (the whole job board content might be wrong). I'll keep both bugs open though, as it's not sure whether 12$ or 25$ is the correct salary.

**Comment by jhovgaard** [comment] 2021-07-06 16:14
Fixed in build 75

**Closed by jhovgaard** 2021-07-06 16:14 UTC
Labels: confirmed
