### ISSUE TITLE
Game Freezes after placing Fridge in a different room.

### ISSUE THREAD

**Issue by Kevintjuhz** [hovgaardgames/bigambitions-public#382] opened 2021-07-30 23:55 UTC
I tried to place a fridge in one of the adjoining rooms. After I had placed it while being in another room then the fridge. The game just froze. 
![image](https://user-images.githubusercontent.com/26409850/127721868-fb3fbf56-79c8-4387-8ca5-a536043a3e40.png)

**Comment by Gerwanese** [comment] 2021-07-31 00:04
@Kevintjuhz I can't reproduce the issue. Can you make sure you didn't accidentally pause the game? You would see it at the top, the game is paused if the pause symbol is white instead of grey. Here in my screenshot it's paused:
![grafik](https://user-images.githubusercontent.com/17579552/127722173-101444e0-27a1-4cfa-a28c-9fb1a439a1ba.png)
This can easily happen if you press the space key.

**Comment by jhovgaard** [comment] 2021-09-09 13:41
Closing for now :-)

**Closed by jhovgaard** 2021-09-09 13:41 UTC
