### ISSUE TITLE
Task "has no opening hours defined" not removed for fast food restaurant

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#172] opened 2021-06-13 20:46 UTC
Build 55

After filling up stock, setting up opening hours and employing somebody, all open tasks are removed - except for the "has no opening hours defined" task which is still shown.

https://user-images.githubusercontent.com/17579552/121821430-2e132000-cc99-11eb-926c-ecd5227f01c8.mp4

**Comment by Gerwanese** [comment] 2021-06-13 20:56
Task was removed after longer waiting time. It seems the task system has quite a delay.

**Comment by jhovgaard** [comment] 2021-07-06 14:39
Unable to reproduce. Probably fixed in build 75.

**Closed by jhovgaard** 2021-07-06 14:39 UTC
Labels: confirmed
