### ISSUE TITLE
Recruitment Campaign not fulfilled

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#219] opened 2021-06-20 00:00 UTC
Build 66

For my first shop (several days ago) I had a 5 day recruitment campaign which was fulfilled on the last day.
Now, for the second shop, I ordered a 1 day recruitment campaign (3 employees) but it's not fulfilled after even a whole week. Recruitment is still shown as active in Recruitment Agency.

![grafik](https://user-images.githubusercontent.com/17579552/122658022-dd079e00-d168-11eb-8b3d-30f2c0633a9c.png)

![grafik](https://user-images.githubusercontent.com/17579552/122658034-ee50aa80-d168-11eb-9818-055924a63309.png)

**Comment by jhovgaard** [comment] 2021-06-23 13:17
Fixed in build 68

**Comment by Gerwanese** [comment] 2021-06-24 19:17
Unfortunately not completely fixed in buid 68.
I tried twice. The first time, I got two candidates during the following day but the third one was missing. Then I reloaded and tried again, this time only getting one candidate out of three.

**Comment by jhovgaard** [comment] 2021-06-24 20:33
Caused by build number mess up. Should be fixed.

**Comment by Gerwanese** [comment] 2021-06-24 21:07
https://www.taiwantrip.info/bigambitions/share/
Video and the original savegame :)
Car is in front of apartment. Drive to recruitment agency, cancel active contract, get a new one, drive back home and sleep.

**Comment by jhovgaard** [comment] 2021-06-24 21:52
Caused by `EmployeeHelper.cs:67` throwing
`InvalidOperationException: Sequence contains more than one matching element`

**Comment by jhovgaard** [comment] 2021-06-25 08:52
Finally fixed in Build 70

**Comment by Gerwanese** [comment] 2021-07-15 19:55
Have to reopen this in build 78.
Three times I could verify that something is wrong (a few other times it was correct).
Two times I ordered 5 candidates within one working day, one time I ordered 10 candidates within one working day.
With the 10 candidates I think I only got 7 or 8 (not 100% sure as bug #322 occured during that time).
With the 5 candidates, both times I only got 4 messages and even the following day the recruitment contract was still active.

All times I ordered candidates for my 24h Hypermarket.
It does not matter whether I'm sleeping during the time or not (bug occured in both cases).

[Build78-WeWantYOUForHypermarket!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6825902/Build78-WeWantYOUForHypermarket.txt)

**Comment by jhovgaard** [comment] 2021-07-19 11:00
Fixed in build 79.

The issue was caused by another bug, stopping the recruitment code from completing, so we'll probably see this happen in the future.

I'll ship the next build in development state, so you'll be able to see errors being thrown in the console.

**Closed by jhovgaard** 2021-07-19 11:00 UTC
Labels: confirmed
