### ISSUE TITLE
Food Stealing

### ISSUE THREAD

**Issue by CoolGingerGinger** [hovgaardgames/bigambitions-public#439] opened 2021-08-05 23:58 UTC
Build 139 (and previous builds) 

You can steal food from the grocery store as shown below. You can purchase and pay for one item and then pick up additional items in your paper bag and walk out without paying for them.

I confirmed this is the case with both grocery stores and gift shops. I believe this issue could be simply fixed by not allowing unpurchased items into paper bags, because the cash register wont let you purchase items in the paper bag anyways. 

This does not happen in the appliance store. (although appliance store is missing the red warning about needing to pay before leaving) 

![stealing food](https://user-images.githubusercontent.com/88410729/128435939-84059421-b7c1-4d0c-8023-e8c43b66df0d.png)

**Comment by Gerwanese** [comment] 2021-08-06 00:04
Duplicate of bug #20 (stealing).
The missing red warning message was reported for the Metro Wholesales already in bug #401; I have added the Appliance Store to that bug now.
I'm closing this bug as all of it is covered by other bugs.

**Closed by Gerwanese** 2021-08-06 00:04 UTC

**Comment by CoolGingerGinger** [comment] 2021-08-06 00:09
Thanks. I tried to look for it, but I did not go all the way back into the early early bugs. Thanks for the work you are doing
