### ISSUE TITLE
KingSizeBed Impossible to place in the apartment

### ISSUE THREAD

**Issue by Zatoici** [hovgaardgames/bigambitions-public#534] opened 2021-09-04 15:28 UTC
I think the video and the title says it all.

Build 184

https://user-images.githubusercontent.com/90038819/132099759-ad729117-faf7-400e-860c-4a81031c64c0.mp4

**Comment by jokoho48** [comment] 2021-09-04 15:29
duplicate of: https://github.com/hovgaardgames/bigambitions-public/issues/489

**Closed by jokoho48** 2021-09-04 15:29 UTC
Labels: duplicate
