### ISSUE TITLE
Parking ticket issued while I'm in the car - and multiple per day

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#272] opened 2021-07-03 18:25 UTC
Build 73

If I'm in my car but stationary I will get a parking ticket. This can even happen when waiting in a traffic jam as long as you don't move.
Besides, I can get an unlimited amount of parking tickets and not just one per day.

[Build71-TicketArmageddon.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758870/Build71-TicketArmageddon.txt)

https://user-images.githubusercontent.com/17579552/124363644-c8350b00-dc3c-11eb-855f-3e6cf9e8ff7b.mp4

**Comment by jhovgaard** [comment] 2021-07-06 10:42
Fixed issue with tickets while driving in build 75. Couldn't reproduce multiple tickets per day.

**Comment by Gerwanese** [comment] 2021-07-07 15:31
Build 75

Ticket while in the car seems to be fixed. Multiple tickets per day still issued however.
In the attached savegame you already have one ticket issued at 02:00 (day 13). If you just wait for the next full hour (because tickets are only issued at full hour), you will get a second ticket.

[Build75-DoubleParkingTicket.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778437/Build75-DoubleParkingTicket.txt)


https://user-images.githubusercontent.com/17579552/124787822-1867e200-df49-11eb-833b-4c3696ccc073.mp4

**Comment by jhovgaard** [comment] 2021-07-08 13:31
Fixed in build 76

**Closed by jhovgaard** 2021-07-08 13:31 UTC
Labels: confirmed
