### ISSUE TITLE
Stock Balance doesnt update during time warp

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#345] opened 2021-07-21 14:38 UTC
Alpha 4 - Build 85

While working at your gift shop and your time warp your shift you don't see any customers coming in, and your stock on every item doesn't go down, so it appears that you didn't receive any customers, however at midnight you do receive some income.

EDIT: Stock does go down, however, the balance on display doesn't update until you leave the store and re-enter.

**Comment by Gerwanese** [comment] 2021-07-21 14:42
Confirmed. Actually a duplicate of #332 but this bug has the correct description, so I'll close #332.

[Build75-GiftshopNoCustomers.txt](https://github.com/hovgaardgames/bigambitions-public/files/6854772/Build75-GiftshopNoCustomers.txt)

**Comment by jhovgaard** [comment] 2021-07-26 14:07
Fixed in build 89

**Closed by jhovgaard** 2021-07-26 14:07 UTC
Labels: confirmed
