### ISSUE TITLE
No worker in shop after my shift.

### ISSUE THREAD

**Issue by Albrat32** [hovgaardgames/bigambitions-public#387] opened 2021-07-31 10:22 UTC
When you work at the shop and your shift finishes.  If you try to purchase goods at the shop... there is no worker to serve you as you finished working at 16.00 and no new worker has turned up to run the shop.

NB : walking outside and back in makes the new worker spawn.

Build 123 Alpha 5

**Comment by Gerwanese** [comment] 2021-07-31 10:25
Duplicate of #227

**Closed by Gerwanese** 2021-07-31 10:25 UTC
Labels: duplicate
